---
- name: Deploy and Configure Prometheus, Grafana, Alertmanager, Nginx, and Node Exporter on Fedora
  hosts: localhost
  become: true
  vars:
    grafana_version_fedora: "{{ grafana_version_stage }}"
    grafana_version_fedora: "{{ grafana_version_prod }}"
  roles:
    - ansibletask1-role
